# Use new container infrastructure to enable caching
sudo: false

language: generic

env:
  - SH=bash AGDA_VERSION=2.6.0 AGDA_STDLIB_VERSION=1.1

cache:
  directories:
  - $HOME/.stack
  - $HOME/.agda
  - $HOME/.local
  - $HOME/agda-$AGDA_VERSION
  - $HOME/agda-stdlib-$AGDA_STDLIB_VERSION

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Download and install agda, agda-stdlib, and agda2html
- make travis-setup

script:
- agda --version
- make

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: ./docs
